
services:

  postgres:
    image: postgres:latest
    container_name: restaurant_care_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_care_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  restaurant-care:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "9000:9000"
    environment:
      KTOR_POSTGRES_URL: jdbc:postgresql://postgres:5432/restaurant_care_db
      KTOR_POSTGRES_USER: postgres
      KTOR_POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: